### ISSUE TITLE
Error in Combining Operation Tables

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/bobcats#1]
https://github.com/LaraVolski/bobcats/blob/46aeb4da9370f6510d48ba4e567ec5289110d1ab/setting_up_operation_tables.rmd#L62

Hi Kaitlyn,

Hoping to shoot an R question your way!

When I run the code on line 62, I get the following error: 
"Error: Names must be unique.
These names are duplicated:
  * "Problem2_from" at locations 10 and 22.
  * "Problem2_to" at locations 11 and 23."

I'm wondering if this is because of the code I added on line 52 in order to account for a gap in dates between phase 3 and phase 4. 

Also, within the code chunk starting on line 62, I added 'Problem_5' to account for the addition of phase 4.

Thank you so much for your help on this! I'm looking forward to taking data science classes at UW & sharpening my skills.
Best,
Lara

**Comment by kaitlyngaynor** [comment]
The issue arose because there was a Problem2_to and Problem2_from column in the phase 4 sheet but you didn't rename them when you brought them in. I've corrected it here, and also made the necessary changes throughout the script! https://github.com/LaraVolski/bobcats/commit/1279efc05c6ca89ed945668b6bf4e063dab4be66

Also fixed another issue I found that would have caused headaches down the road https://github.com/LaraVolski/bobcats/commit/bb9b49acfe6ce128340011422c67cd94c7a02115
